### ISSUE TITLE
About sudo mn --wifi ping Destination Host Unreachable

### ISSUE THREAD

**Issue by qooooo08** [ramonfontes/mn-wifi-book-pt#2]
![image](https://user-images.githubusercontent.com/46881926/121731817-00f13100-cb24-11eb-8402-b14c1af8005c.png)

I'm a beginner for Mininet-Wifi , Maybe two days.. I don’t know why, and I can’t find the reason. I used the sudo mn –wifi to build simulation network, but sta1 ping sta2 Destination Host Unreachable!!!

**Comment by ramonfontes** [comment]
Hello,

Is this issue related to the mn-wifi book?

**Comment by qooooo08** [comment]
It doesn't matter.. I just try to connect and learn Mininet-Wifi. Did I do something wrong?:(

**Comment by ramonfontes** [comment]
It matters, cause there is an appropriate site for questions about mn-wifi. The mailing list! You have opened an issue in the mn-wifi book repository.
