### ISSUE TITLE
Verifying connect between two stations in mininet-wifi

### ISSUE THREAD

**Issue by SalarJamal** [ramonfontes/mn-wifi-book-pt#3]
i created wifi linear topology with 2 wireless stations and 3 access points,
sta1 connected to ap1, ap1 to ap2, ap2 to ap3, ap3 to sta2. 
i make sta1 ping sta2 but it shows destination host unreachable.
sta1 ping ap3 worked without problem.
why the stations cannot ping each others?
i want also to compare it with installing controller.

**Comment by ramonfontes** [comment]
Hi,

You are not pinging to AP. You are actually pinging to localhost (can you check the destination ip addr?). Please keep in mind that ovs doesn't support NS. Regarding the lack of connectivity I suggest you to verify the connection between stations and AP.

**Comment by SalarJamal** [comment]
thanks for your reply
pinging from stations to access points don't have any problem, but stations cannot ping each others.

source code:
#!/usr/bin/python

from mininet.log import setLogLevel, info
from mn_wifi.net import Mininet_wifi
from mn_wifi.node import Station, OVSKernelAP
from mn_wifi.cli import CLI
from mn_wifi.link import wmediumd
from mn_wifi.wmediumdConnector import interference
from subprocess import call


def myNetwork():

    net = Mininet_wifi(topo=None,
                       build=False,
                       link=wmediumd,
                       wmediumd_mode=interference,
                       ipBase='10.0.0.0/8')

    info( '*** Adding controller\n' )
    info( '*** Add switches/APs\n')
    ap1 = net.addAccessPoint('ap1', cls=OVSKernelAP, ssid='ap1-ssid',
                             channel='1', mode='g', position='290.0,235.0,0')
    ap2 = net.addAccessPoint('ap2', cls=OVSKernelAP, ssid='ap2-ssid',
                             channel='1', mode='g', position='498.0,237.0,0')
    ap3 = net.addAccessPoint('ap3', cls=OVSKernelAP, ssid='ap3-ssid',
                             channel='1', mode='g', position='719.0,240.0,0')

    info( '*** Add hosts/stations\n')
    sta1 = net.addStation('sta1', ip='10.0.0.1',
                           position='147.0,412.0,0')
    sta2 = net.addStation('sta2', ip='10.0.0.2',
                           position='869.0,414.0,0')

    info("*** Configuring Propagation Model\n")
    net.setPropagationModel(model="logDistance", exp=3)

    info("*** Configuring wifi nodes\n")
    net.configureWifiNodes()

    net.plotGraph(max_x=1000, max_y=1000)

    info( '*** Starting network\n')
    net.build()
    info( '*** Starting controllers\n')
    for controller in net.controllers:
        controller.start()

    info( '*** Starting switches/APs\n')
    net.get('ap1').start([])
    net.get('ap2').start([])
    net.get('ap3').start([])

    info( '*** Post configure nodes\n')

    CLI(net)
    net.stop()


if __name__ == '__main__':
    setLogLevel( 'info' )
    myNetwork()

**Comment by ramonfontes** [comment]
> pinging from stations to access points don't have any problem

Ovs doesn't support NS! :( Can you check the destination ip address please??

> but stations cannot ping each others.

Did you follow my recommendation?? Did you check the association between station and ap??

**Comment by ramonfontes** [comment]
By the way, where is the link among APs in your code??

**Comment by SalarJamal** [comment]
Thanks for your help, I made links between APs and understood the working principle of OVS.
