### ISSUE TITLE
Network with STP can't connect to external VM!

### ISSUE THREAD

**Issue by SalarJamal** [ramonfontes/mn-wifi-book-pt#4]
Hi dear,
I am working on a scenario in Mininet-WiFi VM shown in figure bellow, I connected s5 to external Linux VM by adding external interface, but when I make ping form h1 or h2 to the external host it shows "destination host unreachable". h1 and h2 can ping each other successfully. I am running Ryu controller with "simple_switch_stp_13.py".
btw, when I removed link 1 and link 2 and running "simple_switch_13.py" the hosts h1 and h2 can ping the external Linux VM without any problem.
Why a network with STP not connect to external VM?
yours sincerely, 
![STP_Problem](https://user-images.githubusercontent.com/90519454/200491598-ed44b917-2c8a-4b70-b2b5-00a2d02dc780.JPG)

**Comment by ramonfontes** [comment]
Closing because this is not a mn-wifi book issue
