### ISSUE TITLE
Mininet Delay Type

### ISSUE THREAD

**Issue by SalarJamal** [ramonfontes/mn-wifi-book-pt#5]
What is the type of delay in Mininet (shown in attached figure)?
is it propagation delay or packet transmission delay or what?
what is the minimum allowed delay value can be set in this field?
![MinDelay](https://user-images.githubusercontent.com/90519454/235374284-dcfd4622-1681-493f-9f3d-5a33a9605acd.JPG)

**Comment by ramonfontes** [comment]
This is not a question about the mn-wifi book. :(
